kpaas_portal/manager/models.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

kpaas_portal/myapp/models.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

kpaas_portal/ceph/forms.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class BucketCreateForm(Form):
    """
    注册 Ceph S3 Bucket
    """
    name = StringField(label=u"Bucket 名称", validators=[DataRequired(message=u"请填写 Bucket 名称.")])

    submit = SubmitField(label=u"注册")

kpaas_portal/cluster/forms.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Required


class ClusterCreateForm(Form):
    """
    创建集群
    """
    cluster_description = StringField(label=u"集群描述", validators=[DataRequired(message=u"请填写集群描述。")])
    cluster_type = SelectField(label=u"节点数量",
                               choices=[(3, u"3 节点"),
                                        (8, u"8 节点"),
                                        (16, u"16 节点"),
                                        (20, u"20 节点")],
                               default=3, validators=[Required(u"请选择节点数量。")])
    cluster_machine = SelectField(label=u"节点配置",
                                  choices=[
                                      ("t", u"Tiny (4C CPU, 8G MEM)"),
                                      ("s", u"Small (8C CPU, 16G MEM)"),
                                      ("m", u"Normal (12C CPU, 32G MEM)"),
                                      ("l", u"Large (16C CPU, 32G MEM)")],
                                  default="ss", validators=[Required(u"请选择节点配置。")])
    submit = SubmitField(label=u"创建集群")


class ClusterDeployForm(Form):
    """
    部署集群
    """
    submit = SubmitField(label=u"开始部署")


class ClusterPublishForm(Form):
    """
    发布集群
    """
    submit = SubmitField(label=u"确认发布")


class ClusterDeleteForm(Form):
    """
    删除集群
    """
    submit = SubmitField(label=u"彻底删除集群")

kpaas_portal/manager/forms.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class FindBucketForm(Form):
    """
    查询 ceph s3 的 bucket
    """
    ceph_username = StringField(label=u'User ID', validators=[DataRequired(message=u'请填写用户名称.')])
    ceph_access_key = StringField(label=u'Access Key', validators=[DataRequired(message=u'请填写 Access Key.')])
    ceph_secret_key = StringField(label=u'Secret key', validators=[DataRequired(message=u'请填写Secret key.')])
    submit = SubmitField(label=u'查询')

kpaas_portal/myapp/forms.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

kpaas_portal/tools/forms.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

from flask_wtf import Form
from wtforms import StringField, SubmitField, FileField, SelectField
from wtforms.validators import DataRequired


class TaskCreateForm(Form):
    """
    创建 MR 任务
    """
    upload_file = FileField(label=u"上传 Jar 文件")

    task_job_input = StringField(label=u"输入路径", validators=[DataRequired(message=u'请填写输入路径')])
    task_job_output = StringField(label=u"输出路径", validators=[DataRequired(message=u'请填写输出路径')])
    task_job_mapClass = StringField(label=u"Map Class 参数", validators=[DataRequired(message=u'请填写输入 Map Class 参数')])
    task_job_reduceClass = StringField(label=u"Reduce Class 参数",
                                       validators=[DataRequired(message=u'请填写输入 Reduce Class 参数')])
    task_job_keyClass = StringField(label=u"Key Class 参数", validators=[DataRequired(message=u'请填写输入 Key Class 参数')])
    task_job_valueClass = StringField(label=u"Value Class 参数",
                                      validators=[DataRequired(message=u'请填写输入 Value Class 参数')])

    submit = SubmitField(label=u'创建 MR 任务')


class HiveTableCreateForm(Form):
    """
    创建 Hive 表
    """
    table_name = StringField(label=u'输入表名，注意不能重名，默认为 mr_ 加 任务id，如：mr_1')
    table_fields = StringField(label=u'输入表结构，如: word STRING, count INT', validators=[DataRequired(message=u'请填写表结构')])
    table_field_separator = StringField(label=u'输入分割符，如: 竖线或逗号等，默认为空格分隔')

    submit = SubmitField(label=u'创建 Hive 表')


class HiveTableCreateFromS3Form(Form):
    """
    S3 创建 Hive 表
    """

    cluster_id = SelectField(label=u"可用集群", choices=[], validators=[DataRequired(u"请选一个集群")], coerce=int)
    table_name = StringField(label=u'输入表名，注意不能重名，默认为 mr_ 加 任务id，如：mr_1')
    table_fields = StringField(label=u'输入表结构，如: word STRING, count INT', validators=[DataRequired(message=u'请填写表结构')])
    table_field_separator = StringField(label=u'输入分割符，如: 竖线或逗号等，默认为空格分隔')

    submit = SubmitField(label=u'创建 Hive 表')

kpaas_portal/api_1_0/__init__.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

kpaas_portal/api_1_1/__init__.py
# -*- coding: utf-8 -*-

"""
    kpaas-portal.__init__.py
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

kpaas_portal/ceph/__init__.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

kpaas_portal/ceph/views.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~
    
    Author: Y.Z.Y
    
"""

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required

from kpaas_portal.extensions import cache
from kpaas_portal.utils.cephtools import CephClass
from kpaas_portal.ceph.forms import BucketCreateForm
from kpaas_portal.ceph.models import Bucket

ceph = Blueprint("ceph", __name__)


@ceph.route("/buckets")
@login_required
# @cache.cached(timeout=60)
def view_ceph_buckets():
    ceph_keys = (current_user.ceph_keys).split()
    ceph_instance = CephClass(ceph_keys[1], ceph_keys[2])
    buckets = ceph_instance.get_all_buckets()

    return render_template("ceph/index.html", buckets=buckets)


@ceph.route("/<bucket>")
@login_required
# @cache.cached(timeout=60)
def view_ceph_objects(bucket):
    ceph_keys = (current_user.ceph_keys).split()

    ceph_instance = CephClass(ceph_keys[1], ceph_keys[2])
    buckets = ceph_instance.get_all_buckets()
    b = ceph_instance.get_bucket_by_name(bucket)
    if b:
        content = ceph_instance.get_bucket_content(b)
    else:
        content = 'Empty!'
    return render_template('ceph/index.html', buckets=buckets, bucket=bucket, content=content)


@ceph.route('/')
# @cache.cached(timeout=60)
def index():
    _buckets = Bucket.query.filter_by(owner=current_user.id).all()

    return render_template('ceph/index.html', buckets=_buckets)


@ceph.route('/buckets/<bucket_id>')
# @cache.cached(timeout=60)
def view_bucket(bucket_id):
    objects = []
    bucket = Bucket.query.filter_by(id=bucket_id).first()
    if bucket:
        objects = bucket.list_objects()

    return render_template('ceph/bucket.html', bucket=bucket, objects=objects)


@ceph.route('/create', methods=['GET', 'POST'])
def create_bucket():
    form = BucketCreateForm()

    if form.validate_on_submit():
        bucket = Bucket()
        bucket.name = form.name.data
        bucket.owner = current_user.id
        bucket.save()
        bucket.register_dns()

        return redirect(url_for('ceph.view_ceph_buckets'))

    return render_template('ceph/create_bucket.html', form=form)

kpaas_portal/cluster/__init__.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

kpaas_portal/cluster/views.py
# -*- coding: utf-8 -*-
"""
    kpaas
    ~~~~~~~~~~~~~~~

    Author: Y.Z.Y

"""

import Queue

from flask import (Blueprint, render_template, redirect, url_for, flash, request, logging, current_app)
from flask_login import login_required, current_user

from .forms import ClusterCreateForm, ClusterDeployForm, ClusterDeleteForm
from .models import Cluster, Pod, Service, StatefulSet

from kpaas_portal.extensions import cache
from kpaas_portal.utils.ambaritools import AmbariServiceClass
from kpaas_portal.utils.k8stools import celery_node_delete, celery_cluster_create, celery_cluster_deploy
from kpaas_portal.utils.haproxytools import HaproxyServiceClass

from kpaas_portal.api_1_1.models import KubeApiService, AmbariApiService

cluster = Blueprint('cluster', __name__)
mylogger = logging.getLogger('app')


def mp_deploy_node(node_name, node_cluster, node_namespace, node_type='agent'):
    agent_pod = Pod(node_type, node_cluster, node_name)
    agent_pod.save()
    celery_cluster_create.apply_async(args=[node_namespace, agent_pod.id])


@cluster.route('/')
@login_required
def index():
    """
    获取集群的列表
    """
    clusters = Cluster.query.filter_by(owner=current_user.id).order_by(Cluster.id.desc()).all()
    k = KubeApiService(host=current_app.config['K8S_SERVICE_ADDR'], port=current_app.config['K8S_SERVICE_PORT'])
    for cluster in clusters:
        services = cluster.services.all()
        for service in services:
            res = k.view_service(service.namespace, service.name)
            if res and len(res['spec']['ports']) > 0:
                current_app.logger.debug('nodeport is: {}'.format(res['spec']['ports'][0]['nodePort']))
                cluster.status = 'ready'
                cluster.save()
            else:
                cluster.status = 'error'
                cluster.save()
        statefulsets = cluster.statefulsets.all()
        for ss in statefulsets:
            res = k.view_statefulset(ss.namespace, ss.name)
            if res and int(res['status'].get('replicas',0)) == int(cluster.type):
                current_app.logger.debug('statefulset replicas is: {}'.format(int(res['status'].get('replicas',0))))
                cluster.current_nodes = int(res['status'].get('replicas',0))
                cluster.status = 'ready'
                cluster.save()
            else:
                cluster.status = 'error'
                cluster.save()

        current_app.logger.debug('view cluster id: {0}, service is: {1}, statefulset is: {2}'.format(cluster.id, services, statefulsets))

    return render_template('cluster/index.html', clusters=clusters)


@cluster.route('/create', methods=['GET', 'POST'])
@login_required
def create_cluster():
    """
    创建集群
    """
    if not current_app.config['CEPH_CLOSED'] and not current_user.ceph_keys:
        flash(u'失败！当前用户没有配置 Ceph S3 Key，请配置账户信息。', 'danger')
        return redirect(current_user.url)
    form = ClusterCreateForm()
    if request.method == 'POST':
        # 初始化一个集群信息
        current_app.logger.debug('create cluster: description is {0}, type is {1}, machine is {2}'.format(form.cluster_description.data,
                                                                                                          form.cluster_type.data,
                                                                                                          form.cluster_machine.data))
        # write into db: cluster
        cluster_instance = Cluster(form.cluster_description.data, form.cluster_type.data, form.cluster_machine.data)
        cluster_instance.save(current_user)
        cluster_instance.name = 'cluster{0}'.format(cluster_instance.id)
        cluster_instance.status = 'pending'
        cluster_instance.save(current_user)
        # jobs queue
        q = Queue.Queue()
        # write into db: service
        server_service = Service(current_user.namespace, cluster_instance)
        server_service.status = 'pending'
        server_service.save()
        q.put({'id': int(server_service.id), 'type': 'service', 'data': server_service.get_server_json})
        # write into db: server statefulset
        server_statefulset = StatefulSet(current_user.namespace, cluster_instance, '{}-server'.format(cluster_instance.name), 'ambari-server', replicas=1)
        server_statefulset.status = 'pending'
        server_statefulset.save()
        q.put({'id': server_statefulset.id, 'type': 'statefulset', 'data': server_statefulset.parse('ambari-server')})
        # write into db: agent statefulset
        agent_statefulset = StatefulSet(current_user.namespace, cluster_instance, '{}-agent'.format(cluster_instance.name), 'ambari-agent', replicas=3)
        agent_statefulset.status = 'pending'
        agent_statefulset.save()
        q.put({'id': agent_statefulset.id, 'type': 'statefulset', 'data': agent_statefulset.parse('ambari-agent')})
        while not q.empty():
            job = q.get()
            current_app.logger.debug('job is: {}'.format(job))
            id = job.get('id', 0)
            type = job.get('type')
            data = job.get('data')
            current_app.logger.debug('post data: {}'.format(data))
            k = KubeApiService(host=current_app.config['K8S_SERVICE_ADDR'], port=current_app.config['K8S_SERVICE_PORT'])
            if type == 'service' and id and isinstance(data, dict):
                k.create_service(namespace=current_user.namespace, data=data)
                s = Service.query.get(id)
                s.status = 'created'
                s.save()
            if type == 'statefulset' and id and isinstance(data, dict):
                k.create_statefulset(namespace=current_user.namespace, data=data)
                ss = StatefulSet.query.get(id)
                ss.status = 'created'
                ss.save()
            cluster_instance.status = 'created'
            cluster_instance.save()
        return redirect(url_for('cluster.index'))
    return render_template('cluster/cluster_create.html', form=form)


@cluster.route('/<cluster_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_cluster(cluster_id):
    """
    删除集群
    """
    cluster_instance = Cluster.query.get(cluster_id)
    form = ClusterDeleteForm()
    if form.validate_on_submit():
        k = KubeApiService(host=current_app.config['K8S_SERVICE_ADDR'], port=current_app.config['K8S_SERVICE_PORT'])
        # delete all services
        services = cluster_instance.services.all()
        for service in services:
            k.delete_service(service.namespace, service.name)
            current_app.logger.debug('delete service is: {0}'.format(service.name))
        # delete all statefulsets
        statefulsets = cluster_instance.statefulsets.all()
        for ss in statefulsets:
            k.delete_statefulset(ss.namespace, ss.name)
            for i in range(0, int(ss.replicas)):
                k.delete_pod(ss.namespace, '{0}-{1}'.format(ss.name, i))
            current_app.logger.debug('delete statefulset is: {0}'.format(ss.name))
        # db delete all cluster records
        cluster_instance.delete()
        flash(u'成功！集群 {0} 被删除。'.format(cluster_instance.name), 'success')
        return redirect(url_for('cluster.index'))
    return render_template('cluster/cluster_delete.html', cluster=cluster_instance, form=form)


@cluster.route('/<cluster_id>/deploy', methods=['GET', 'POST'])
@login_required
def deploy_cluster(cluster_id):
    """
    部署集群
    """
    cluster_instance = Cluster.query.get(cluster_id)
    if cluster_instance.cluster_deployment != 0:
        flash(u'失败！集群 {} 已经部署过了，不能重新部署，请查看。'.format(cluster_instance.name), 'danger')
    if not cluster_instance.status == 'ready':
        flash(
            u'失败！集群 {} 节点资源还没有准备好，请查看。'.format(cluster_instance.name), 'danger')
    sss = []
    k = KubeApiService(host=current_app.config['K8S_SERVICE_ADDR'], port=current_app.config['K8S_SERVICE_PORT'])
    # get server info
    server_name = '{0}-server-0'.format(cluster_instance.name)
    server_fullname = '{0}.node.{1}.svc.cluster.local'.format(server_name, current_user.namespace)
    server_info = k.view_pod(current_user.namespace, server_name)
    sss.append({
        'name': server_fullname,
        'ip': server_info['status'].get('podIP', ''),
        'status': server_info['status'].get('phase', ''),
        'register': False
    })
    current_app.logger.debug(
        'cluster is: {0}, server pod is: {1}, data is: "{2}"'.format(cluster_instance.name, server_name, server_info))
    # get agents info
    ambari_instance = AmbariApiService('42.123.106.18', 10011)
    nodes = ambari_instance.register_nodes()
    ambari_nodes = []
    if nodes['items']:
        ambari_nodes = [n['Hosts']['host_name'] for n in nodes['items']]
    current_app.logger.debug('ambari register nodes is: "{}"'.format(ambari_nodes))
    for i in range(0, int(cluster_instance.current_nodes)):
        agent_name = '{0}-agent-{1}'.format(cluster_instance.name, i)
        agent_fullname = '{0}.node.{1}.svc.cluster.local'.format(agent_name, current_user.namespace)
        is_register = False
        if agent_fullname in ambari_nodes:
            is_register = True
        agent_info = k.view_pod(current_user.namespace, agent_name)
        sss.append({
            'name': agent_fullname,
            'ip': agent_info['status'].get('podIP', ''),
            'status': agent_info['status'].get('phase', ''),
            'register': is_register
        })
        current_app.logger.debug(
            'cluster is: {0}, agent pod is: {1}, data is: "{2}"'.format(cluster_instance.name, agent_name, agent_info))
    form = ClusterDeployForm()
    if form.validate_on_submit():
        cluster_instance.cluster_deployment = 1
        cluster_instance.status = 'deploying'
        cluster_instance.save()
        flash(u'成功！集群 {0} 已经提交部署。'.format(cluster_instance.name), 'success')
        return redirect(url_for('cluster.index'))

kpaas_portal/templates/ceph/bucket.html
{% extends "layout.html" %}

{% block content %}
    <div class="forum-view">
        <ol class="breadcrumb flaskbb-breadcrumb">
            <li>Ceph S3 存储</li>
            <li><a class="btn btn-link" href="{{ url_for('ceph.index') }}">S3 Bucket 列表</a></li>
            <li class="active"><a class="btn btn-link" href="{{ url_for('ceph.view_bucket', bucket_id=bucket.id) }}">{{ bucket.name }}</a></li>
        </ol>

        <div class="row controls-row">
            <div class="pull-left">
            </div>
        </div>

        <div class="panel forum-panel">
            <div class="panel-heading forum-head">
                <span class="fa fa-arrow-circle-right"></span> Object 对象列表
            </div>

            <div class="panel-body forum-body">
                <table class="table table-bordered" style="table-layout: fixed;word-wrap: break-word">
                    <thead style="background: #eaf1f5">
                    <tr>
                        <th>Object 名称</th>
                        <th>Object 大小</th>
                        <th>Object 修改时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if objects %}
                            {% for object in objects %}
                                <tr>
                                    <td>
                                        {{ object['name'] }}
                                    </td>
                                    <td>
                                        {{ object['size'] }}
                                    </td>
                                    <td>
                                        <span class="text text-danger"> {{ object['modified'] }}</span>
                                    </td>
                                    <td>
                                        [<a class="btn btn-link" href="{{ object['url'] }}">下载 <span class="fa fa-download"></span></a>]
                                        [<a class="btn btn-link" href="{{ url_for('tools.hive_s3load_table', bucket_id=bucket.id, input_file=object['name']) }}">导入 Hive <span class="fa fa-info"></span></a>]
                                    </td>
                                </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

kpaas_portal/templates/ceph/create_bucket.html
{% extends "layout.html" %}

{% block content %}
{% from "macros.html" import render_field, render_submit_field %}

    <div class="forum-view">
        <ol class="breadcrumb flaskbb-breadcrumb">
            <li><a class="btn btn-link" href="{{ url_for('main.index') }}">首页</a></li>
            <li>申请 Ceph S3 Bucket 存储</li>
        </ol>
        <div class="panel page-panel">
            <div class="panel-heading">
                <span class="fa fa-arrow-circle-right"></span> 申请 Ceph S3 Bucket 存储
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" method="post">
                    {{ form.hidden_tag() }}

                    {{ render_field(form.name)}}
                    {{ render_submit_field(form.submit)}}
                </form>
            </div>
            <div class="panel-info">
                <p>或者 <a class="btn btn-link" href="{{ url_for('main.index') }}">取消</a> 操作</p>
            </div>
        </div>
    </div>

{% endblock %}

kpaas_portal/templates/ceph/index.html
{% extends "layout.html" %}

{% block content %}
{% from 'macros.html' import render_pagination, topic_pages %}

    <div class="forum-view">
        <ol class="breadcrumb flaskbb-breadcrumb">
            <li>Ceph S3 存储</li>
            <li class="active"><a class="btn btn-link" href="{{ url_for('ceph.index') }}">S3 Bucket 列表</a></li>
        </ol>

        <div class="row controls-row">
            <div class="pull-left">
            </div>
        </div>

        <div class="panel forum-panel">
            <div class="panel-heading forum-head">
                <span class="fa fa-arrow-circle-right"></span> Bucket 列表
            </div>

            <div class="panel-body forum-body">
                <table class="table table-bordered" style="table-layout: fixed;word-wrap: break-word">
                    <thead style="background: #eaf1f5">
                    <tr>
                        <th>Bucket 状态</th>
                        <th>Bucket 名称</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if buckets %}
                            {% for bucket in buckets %}
                                <tr>
                                    <td>
                                        <span class="label label-success">OK</span>
                                        Modify: {{ moment(bucket.created).fromNow() }}
                                    </td>
                                    <td>
                                        <a href="{{ url_for('ceph.view_bucket', bucket_id=bucket.id) }}"> {{ bucket.name }}</a>
                                        <span class="badge"> {{ bucket.objects_count }}</span>
                                    </td>
                                    <td>
                                        {{ moment(bucket.created).format('LLL') }}
                                    </td>
                                    <td>
                                        -
                                    </td>
                                </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}